// packages/react-components/src/Button/Button.tsx
import classnames from 'classnames';

import { palette } from '../theme.js';
import WiredButton, { ButtonProps } from '../wired-elements/WiredButton.js';

export default function Button(props: ButtonProps) {
  const classes = classnames(
    palette.primary.main,
    palette.primary.contrastText,
    palette.primary.hover.main,
    palette.primary.hover.contrastText,
  );
  return (
    <div className={'tw-inline-block'}>
      <WiredButton
        aria-label={props.children}
        className={classes}
        data-testid={props['data-testid'] ?? 'wired-button'}
        onClick={props.onClick}
        role={'button'}
      >
        {props.children}
      </WiredButton>
    </div>
  );
}

// packages/angular-components/projects/ngx-components/src/lib/button/button.component.ts
import 'wired-elements/lib/wired-button';

import { Attribute, Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import cn from 'classnames';

import { generateTestIdWithPrefix, TEST_ID } from '../../test-helpers/test-id';
import { palette } from '../../theme';

@Component({
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  selector: 'ngx-button',
  standalone: true,
  template: `<wired-button class="{{ classNames }}" [attr.data-testid]="testId"
    ><ng-content></ng-content
  ></wired-button>`,
})
export class ButtonComponent {
  testId = 'ngx-button';

  classNames = '';

  constructor(@Attribute(TEST_ID) public testIdSuffix: string) {
    this.classNames = cn(
      'primary',
      palette.primary.main,
      palette.primary.contrastText,
      palette.primary.hover.main,
      palette.primary.hover.contrastText,
    );
    this.testId = generateTestIdWithPrefix({
      id: testIdSuffix,
      prefix: this.testId,
    });
  }
}
